### ISSUE TITLE
boj4344

### ISSUE THREAD

**Issue by alsrb9936** [GyeongHoKim/algorithm#2]
문제
대학생 새내기들의 90%는 자신이 반에서 평균은 넘는다고 생각한다. 당신은 그들에게 슬픈 진실을 알려줘야 한다.

입력
첫째 줄에는 테스트 케이스의 개수 C가 주어진다.

둘째 줄부터 각 테스트 케이스마다 학생의 수 N(1 ≤ N ≤ 1000, N은 정수)이 첫 수로 주어지고, 이어서 N명의 점수가 주어진다. 점수는 0보다 크거나 같고, 100보다 작거나 같은 정수이다.

출력
각 케이스마다 한 줄씩 평균을 넘는 학생들의 비율을 반올림하여 소수점 셋째 자리까지 출력한다.

예제입력
5
5 50 50 70 80 100
7 100 95 90 80 70 60 50
3 70 90 80
3 70 90 81
9 100 99 98 97 96 95 94 93 91

예제출력
40.000%
57.143%
33.333%
66.667%
55.556%

``` c
#include<stdio.h>
int main(){
  int n,i,sum=0,avg=0,count=0;
  double percent;
  int score[1000];
  scanf("%d",&n);
  for(i=0;i<n;i++){
    scanf("%d",&score[i]);
    sum += score[i];
  }

  avg = sum/n;

  for(i=0;i<n;i++){
    if(score[i]>avg){
      count += 1;
      }
  }
  
  percent = count/(double)n * 100;
  printf("%.3lf%%\n",percent);

}
```
잘 모루겟쉐여

**Comment by GyeongHoKim** [comment]
``` c
while(C--)
{
"code"
}
```

테스트 케이스 C에 대한 코드가 없는 것 같습니다!
이런 식으로 해보세용~
