### ISSUE TITLE
BOJ 13023 ABCDE

### ISSUE THREAD

**Issue by GyeongHoKim** [GyeongHoKim/algorithm#32]
# 문제

BOJ 알고리즘 캠프에는 총 N명이 참가하고 있다. 사람들은 0번부터 N-1번으로 번호가 매겨져 있고, 일부 사람들은 친구이다.

오늘은 다음과 같은 친구 관계를 가진 사람 A, B, C, D, E가 존재하는지 구해보려고 한다.

A는 B와 친구다.
B는 C와 친구다.
C는 D와 친구다.
D는 E와 친구다.
위와 같은 친구 관계가 존재하는지 안하는지 구하는 프로그램을 작성하시오.

입력
첫째 줄에 사람의 수 N (5 ≤ N ≤ 2000)과 친구 관계의 수 M (1 ≤ M ≤ 2000)이 주어진다.

둘째 줄부터 M개의 줄에는 정수 a와 b가 주어지며, a와 b가 친구라는 뜻이다. (0 ≤ a, b ≤ N-1, a ≠ b) 같은 친구 관계가 두 번 이상 주어지는 경우는 없다.

출력
문제의 조건에 맞는 A, B, C, D, E가 존재하면 1을 없으면 0을 출력한다.

예제 입력 1 

> 5 4  
> 0 1  
> 1 2  
> 2 3  
> 3 4  

예제 출력 1 

> 1  

예제 입력 2 

> 5 5  
> 0 1  
> 1 2  
> 2 3  
> 3 0  
> 1 4  

예제 출력 2 

> 1  

# 궁금한 것

문제가 이해되지 않습니다. 제가 이해한 바로는 A-B-C-D-E 와 같은 관계를 만족해야 1인데 왜 예제 입력2가 1이 되는 것인가요??

예제 입력 2 

> 5 5  
> A B  
> B C  
> C D  
> D A  
> B E  

이렇게 나타낼 수 있을 텐데 이러면 A-B-C-D 에서 끊기고 D에서 E를 잇는 간선이 없지 않나요? 0이 나와야 할 것 같은데 의문입니다.

HELP!!!

**Comment by jaeung0527** [comment]
이어진 5개의 정점으로 표현할 수 있기만 하면 됩니다 이름은 임의로 붙인것이니
